local EggTable = {}
local ZoneTable = {}
for _,Egg in pairs(game:GetService("Workspace").Eggs:GetChildren()) do
    table.insert(EggTable, Egg.Name)
end
for _,Zone in pairs(game:GetService("Workspace").Zones:GetChildren()) do
    table.insert(ZoneTable, Zone.Name)
end

game:GetService("Players").LocalPlayer.Idled:connect(function()
	game:GetService("VirtualUser"):Button2Down(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
	wait(1)
	game:GetService("VirtualUser"):Button2Up(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
end)

local Material = loadstring(game:HttpGet("https://raw.githubusercontent.com/Kinlei/MaterialLua/master/Module.lua"))()

local X = Material.Load({
    Title = "KitchenHub | Clicker Simulator",
    Style = 1,
    SizeX = 350,
    SizeY = 350,
    Theme = "Dark",
    ColorOverrides = {
        MainFrame = Color3.fromRGB(163, 11, 11)
    }
})

local Af = X.New({
    Title = "Clicking"
})

local pet = X.New({
    Title = "Pets & Eggs"
})

local teleport = X.New({
    Title = "Teleports"
})

local B = Af.Toggle({
    Text = "Auto-Clicker",
    Callback = function(click)
        AutoClick = click
    end,
    Enabled = false
})

pet.Button({
    Text = "Equip Best pets",
    Callback = function()
        -- Script generated by SimpleSpy - credits to exx#9394

        game:GetService("ReplicatedStorage").Events.Client.petsTools.equipBest:FireServer()
    end
})

pet.Dropdown({
    Text = "Egg",
    Callback = function(eggy)
        SelectedEgg = eggy
    end,
    Options = EggTable
})

pet.Toggle({
    Text = "spam open eggs",
    Callback = function(value)
        OpenEgg = value
    end,
    Enabled = false
})

pet.TextField({
    Text = "Pet to auto-shiny",
    Callback = function(value)
        CombinePetName = value
    end
})

pet.Toggle({
    Text = "Auto-Shiny",
    Callback = function(value)
        AutoShiny = value
    end,
    Enabled = false
})

teleport.Dropdown({
    Text = "zone",
    Callback = function(zone)
        game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").Zones[zone].teleport.CFrame
    end,
    Options = ZoneTable
})

teleport.Button({
    Text = "Teleport Main Zone",
    Callback = function()
        game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").Lobby.teleport.CFrame
    end
})

teleport.Button({
    Text = "Teleport Tech Zone",
    Callback = function()
        game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").techWorld.Portal.teleportPosition.CFrame
    end
})

spawn(function()
    while true do wait()
        if OpenEgg then
            local ohInstance1 = workspace.Eggs[SelectedEgg]
            local ohBoolean2 = false
            local ohBoolean3 = false
            game:GetService("ReplicatedStorage").Events.Client.purchaseEgg2:InvokeServer(ohInstance1, ohBoolean2, ohBoolean3)
        end
    end
end)

spawn(function()
    while true do wait(0.3)
        if AutoShiny then
            local ohString1 = CombinePetName
            local ohNumber2 = 1
            game:GetService("ReplicatedStorage").Events.Client.upgradePet:FireServer(ohString1, ohNumber2, ohInstance3)
        end
    end
end)

spawn(function()
    while true do wait()
        if AutoClick then
            getsenv(game:GetService("Players").LocalPlayer.PlayerGui.mainUI.LocalScript).activateClick()
        end
    end
end)